### ISSUE TITLE
Todo: pybadge gui

### ISSUE THREAD

**Issue by LuckyTurtleDev** [LuckyTurtleDev/m3#13]
simple gui to select cards

- [x] select cards
- [x] line break cards
- [x] send cards to pc
- [x] remove cards
- [x] count of wait card
- [x] game over screen
- [x] load level (currently hardcoded)
- [x] retrys (keep previous solution, but allow editing)
