### ISSUE TITLE
Todo: map v3

### ISSUE THREAD

**Issue by LuckyTurtleDev** [LuckyTurtleDev/m3#15]
- [ ] The tmx map needs an way to define available cards for the current level.
- [x] We also need an option to define the start rotation of the players cars.
- [ ] Migrate from `self-rust-tokenize` to `serde`

Looks like `self-rust-tokenize` does always try to use `Vec`. This does not work at no-std context. 

implementation suggestions:
* use tmx map properties
